from PyQt5 import QtCore, QtWidgets


# Меню администратора
class adm_menu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 550)
        MainWindow.setMinimumSize(QtCore.QSize(600, 550))
        MainWindow.setMaximumSize(QtCore.QSize(600, 550))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(12, 36, 40, 16))
        self.label.setMinimumSize(QtCore.QSize(40, 16))
        self.label.setMaximumSize(QtCore.QSize(40, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 40, 16))
        self.label_2.setMinimumSize(QtCore.QSize(40, 16))
        self.label_2.setMaximumSize(QtCore.QSize(40, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 80, 70, 16))
        self.label_3.setMinimumSize(QtCore.QSize(70, 16))
        self.label_3.setMaximumSize(QtCore.QSize(70, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 140, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 70, 16))
        self.label_6.setMinimumSize(QtCore.QSize(70, 16))
        self.label_6.setMaximumSize(QtCore.QSize(70, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 140, 60, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(12, 312, 40, 16))
        self.label_8.setMinimumSize(QtCore.QSize(40, 16))
        self.label_8.setMaximumSize(QtCore.QSize(40, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(10, 250, 50, 16))
        self.label_9.setMinimumSize(QtCore.QSize(50, 16))
        self.label_9.setMaximumSize(QtCore.QSize(50, 16))
        self.label_9.setObjectName("label_9")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 50, 240, 30))
        self.textBrowser.setMinimumSize(QtCore.QSize(240, 30))
        self.textBrowser.setMaximumSize(QtCore.QSize(240, 30))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 270, 240, 30))
        self.textBrowser_2.setMinimumSize(QtCore.QSize(240, 30))
        self.textBrowser_2.setMaximumSize(QtCore.QSize(240, 30))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 330, 240, 30))
        self.textBrowser_3.setMinimumSize(QtCore.QSize(240, 30))
        self.textBrowser_3.setMaximumSize(QtCore.QSize(240, 30))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(80, 160, 60, 30))
        self.textBrowser_4.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 160, 60, 30))
        self.textBrowser_5.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_5.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(150, 160, 60, 30))
        self.textBrowser_6.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_6.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(150, 100, 60, 30))
        self.textBrowser_7.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_7.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(80, 100, 60, 30))
        self.textBrowser_8.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_8.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(10, 100, 60, 30))
        self.textBrowser_9.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_9.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(10, 10, 280, 16))
        self.label_10.setMinimumSize(QtCore.QSize(280, 16))
        self.label_10.setMaximumSize(QtCore.QSize(280, 16))
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(9, 369, 60, 16))
        self.label_11.setMinimumSize(QtCore.QSize(60, 16))
        self.label_11.setMaximumSize(QtCore.QSize(60, 16))
        self.label_11.setObjectName("label_11")
        self.textBrowser_10 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_10.setGeometry(QtCore.QRect(9, 389, 240, 30))
        self.textBrowser_10.setMinimumSize(QtCore.QSize(240, 30))
        self.textBrowser_10.setMaximumSize(QtCore.QSize(240, 30))
        self.textBrowser_10.setObjectName("textBrowser_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 470, 40, 16))
        self.label_12.setMinimumSize(QtCore.QSize(40, 16))
        self.label_12.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_12.setObjectName("label_12")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_11.setGeometry(QtCore.QRect(9, 489, 60, 30))
        self.textBrowser_11.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_11.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(79, 469, 40, 16))
        self.label_13.setMinimumSize(QtCore.QSize(40, 16))
        self.label_13.setMaximumSize(QtCore.QSize(40, 16))
        self.label_13.setObjectName("label_13")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_12.setGeometry(QtCore.QRect(79, 489, 80, 30))
        self.textBrowser_12.setMinimumSize(QtCore.QSize(80, 30))
        self.textBrowser_12.setMaximumSize(QtCore.QSize(80, 30))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(170, 470, 30, 16))
        self.label_14.setMinimumSize(QtCore.QSize(30, 16))
        self.label_14.setMaximumSize(QtCore.QSize(30, 16))
        self.label_14.setObjectName("label_14")
        self.textBrowser_13 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_13.setGeometry(QtCore.QRect(9, 439, 240, 30))
        self.textBrowser_13.setMinimumSize(QtCore.QSize(240, 30))
        self.textBrowser_13.setMaximumSize(QtCore.QSize(240, 30))
        self.textBrowser_13.setObjectName("textBrowser_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(9, 419, 90, 16))
        self.label_15.setMinimumSize(QtCore.QSize(90, 16))
        self.label_15.setMaximumSize(QtCore.QSize(90, 16))
        self.label_15.setObjectName("label_15")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_14.setGeometry(QtCore.QRect(169, 489, 80, 30))
        self.textBrowser_14.setMinimumSize(QtCore.QSize(80, 30))
        self.textBrowser_14.setMaximumSize(QtCore.QSize(80, 30))
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(290, 370, 60, 16))
        self.label_16.setMinimumSize(QtCore.QSize(60, 16))
        self.label_16.setMaximumSize(QtCore.QSize(60, 16))
        self.label_16.setObjectName("label_16")
        self.textBrowser_15 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_15.setGeometry(QtCore.QRect(289, 389, 290, 30))
        self.textBrowser_15.setMinimumSize(QtCore.QSize(290, 30))
        self.textBrowser_15.setMaximumSize(QtCore.QSize(290, 30))
        self.textBrowser_15.setObjectName("textBrowser_15")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(370, 470, 30, 16))
        self.label_17.setMinimumSize(QtCore.QSize(30, 16))
        self.label_17.setMaximumSize(QtCore.QSize(30, 16))
        self.label_17.setObjectName("label_17")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_16.setGeometry(QtCore.QRect(369, 489, 70, 30))
        self.textBrowser_16.setMinimumSize(QtCore.QSize(70, 30))
        self.textBrowser_16.setMaximumSize(QtCore.QSize(70, 30))
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_17.setGeometry(QtCore.QRect(289, 489, 70, 30))
        self.textBrowser_17.setMinimumSize(QtCore.QSize(70, 30))
        self.textBrowser_17.setMaximumSize(QtCore.QSize(70, 30))
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(290, 470, 40, 16))
        self.label_18.setMinimumSize(QtCore.QSize(40, 16))
        self.label_18.setMaximumSize(QtCore.QSize(40, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(450, 470, 140, 16))
        self.label_19.setMinimumSize(QtCore.QSize(140, 16))
        self.label_19.setMaximumSize(QtCore.QSize(140, 16))
        self.label_19.setObjectName("label_19")
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_18.setGeometry(QtCore.QRect(449, 489, 130, 30))
        self.textBrowser_18.setMinimumSize(QtCore.QSize(130, 30))
        self.textBrowser_18.setMaximumSize(QtCore.QSize(130, 30))
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(289, 419, 80, 16))
        self.label_20.setMinimumSize(QtCore.QSize(80, 16))
        self.label_20.setMaximumSize(QtCore.QSize(80, 16))
        self.label_20.setObjectName("label_20")
        self.textBrowser_19 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_19.setGeometry(QtCore.QRect(289, 439, 290, 30))
        self.textBrowser_19.setMinimumSize(QtCore.QSize(290, 30))
        self.textBrowser_19.setMaximumSize(QtCore.QSize(290, 30))
        self.textBrowser_19.setObjectName("textBrowser_19")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 220, 280, 26))
        self.comboBox_3.setMinimumSize(QtCore.QSize(280, 26))
        self.comboBox_3.setMaximumSize(QtCore.QSize(280, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(10, 200, 160, 16))
        self.label_23.setMinimumSize(QtCore.QSize(160, 16))
        self.label_23.setMaximumSize(QtCore.QSize(160, 16))
        self.label_23.setObjectName("label_23")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(300, 0, 291, 361))
        self.groupBox.setObjectName("groupBox")
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 210, 16))
        self.label_21.setMinimumSize(QtCore.QSize(210, 16))
        self.label_21.setMaximumSize(QtCore.QSize(210, 16))
        self.label_21.setObjectName("label_21")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setGeometry(QtCore.QRect(10, 50, 280, 26))
        self.comboBox.setMinimumSize(QtCore.QSize(280, 26))
        self.comboBox.setMaximumSize(QtCore.QSize(280, 26))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 70, 280, 34))
        self.pushButton.setMinimumSize(QtCore.QSize(280, 34))
        self.pushButton.setMaximumSize(QtCore.QSize(280, 34))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 240, 280, 34))
        self.pushButton_5.setMinimumSize(QtCore.QSize(280, 34))
        self.pushButton_5.setMaximumSize(QtCore.QSize(280, 34))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 210, 280, 34))
        self.pushButton_4.setMinimumSize(QtCore.QSize(280, 34))
        self.pushButton_4.setMaximumSize(QtCore.QSize(280, 34))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 190, 280, 26))
        self.comboBox_2.setMinimumSize(QtCore.QSize(280, 26))
        self.comboBox_2.setMaximumSize(QtCore.QSize(280, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.label_22 = QtWidgets.QLabel(self.groupBox)
        self.label_22.setGeometry(QtCore.QRect(10, 170, 275, 16))
        self.label_22.setMinimumSize(QtCore.QSize(275, 16))
        self.label_22.setMaximumSize(QtCore.QSize(275, 16))
        self.label_22.setObjectName("label_22")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 130, 280, 34))
        self.pushButton_2.setMinimumSize(QtCore.QSize(280, 34))
        self.pushButton_2.setMaximumSize(QtCore.QSize(280, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 100, 280, 34))
        self.pushButton_3.setMinimumSize(QtCore.QSize(280, 34))
        self.pushButton_3.setMaximumSize(QtCore.QSize(280, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 320, 280, 34))
        self.pushButton_6.setMinimumSize(QtCore.QSize(280, 34))
        self.pushButton_6.setMaximumSize(QtCore.QSize(280, 34))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_24 = QtWidgets.QLabel(self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(0, 280, 290, 16))
        self.label_24.setMinimumSize(QtCore.QSize(290, 16))
        self.label_24.setMaximumSize(QtCore.QSize(290, 16))
        self.label_24.setObjectName("label_24")
        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_4.setGeometry(QtCore.QRect(0, 300, 280, 26))
        self.comboBox_4.setMinimumSize(QtCore.QSize(280, 26))
        self.comboBox_4.setMaximumSize(QtCore.QSize(280, 26))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 80, 100, 16))
        self.label_4.setMinimumSize(QtCore.QSize(100, 16))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное меню администратора"))
        self.label.setText(_translate("MainWindow", "Имя:"))
        self.label_2.setText(_translate("MainWindow", "Сила:"))
        self.label_3.setText(_translate("MainWindow", "Ловкость:"))
        self.label_5.setText(_translate("MainWindow", "Интеллект:"))
        self.label_6.setText(_translate("MainWindow", "Мудрость:"))
        self.label_7.setText(_translate("MainWindow", "Харизма:"))
        self.label_8.setText(_translate("MainWindow", "Раса:"))
        self.label_9.setText(_translate("MainWindow", "Класс:"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Характеристики выбранного персонажа:</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Оружие:"))
        self.label_12.setText(_translate("MainWindow", "Урон:"))
        self.label_13.setText(_translate("MainWindow", "Цена:"))
        self.label_14.setText(_translate("MainWindow", "Вес:"))
        self.label_15.setText(_translate("MainWindow", "Тип оружия:"))
        self.label_16.setText(_translate("MainWindow", "Броня:"))
        self.label_17.setText(_translate("MainWindow", "Вес:"))
        self.label_18.setText(_translate("MainWindow", "Цена:"))
        self.label_19.setText(_translate("MainWindow", "Помеха скрытности:"))
        self.label_20.setText(_translate("MainWindow", "Тип брони:"))
        self.label_23.setText(_translate("MainWindow", "Доступные заклинания:"))
        self.groupBox.setTitle(_translate("MainWindow", "Элементы управления"))
        self.label_21.setText(_translate("MainWindow", "Список доступных персонажей:"))
        self.pushButton.setText(_translate("MainWindow", "Вывести информацию о персонаже"))
        self.pushButton_5.setText(_translate("MainWindow", "Перейти в панель управления БД"))
        self.pushButton_4.setText(_translate("MainWindow", "Выгрузить базу данных"))
        self.label_22.setText(_translate("MainWindow", "Доступные варианты выгрузки БД:"))
        self.pushButton_2.setText(_translate("MainWindow", "Создать нового персонажа"))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить выбранного персонажа"))
        self.pushButton_6.setText(_translate("MainWindow", "Узнать подробности"))
        self.label_24.setText(_translate("MainWindow", "Выберите о чем хотите узнать подробности:"))
        self.label_4.setText(_translate("MainWindow", "Телосложение:"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "Выйти из аккаунта"))