from PyQt5 import QtCore, QtWidgets


# Создание персонажа
class create_per(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 620)
        MainWindow.setMinimumSize(QtCore.QSize(670, 620))
        MainWindow.setMaximumSize(QtCore.QSize(670, 620))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(8, 4, 260, 16))
        self.label_10.setMinimumSize(QtCore.QSize(260, 16))
        self.label_10.setMaximumSize(QtCore.QSize(60, 16))
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName("label_10")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 40, 16))
        self.label.setMinimumSize(QtCore.QSize(40, 16))
        self.label.setMaximumSize(QtCore.QSize(40, 16))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 40, 240, 30))
        self.textEdit.setMinimumSize(QtCore.QSize(240, 30))
        self.textEdit.setMaximumSize(QtCore.QSize(240, 30))
        self.textEdit.setObjectName("textEdit")
        self.textBrowser_6 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_6.setGeometry(QtCore.QRect(150, 140, 60, 30))
        self.textBrowser_6.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_6.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 70, 100, 16))
        self.label_4.setMinimumSize(QtCore.QSize(100, 16))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 120, 60, 16))
        self.label_7.setObjectName("label_7")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_5.setGeometry(QtCore.QRect(10, 140, 60, 30))
        self.textBrowser_5.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_5.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(80, 70, 70, 16))
        self.label_3.setMinimumSize(QtCore.QSize(70, 16))
        self.label_3.setMaximumSize(QtCore.QSize(70, 16))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(150, 120, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 70, 16))
        self.label_6.setMinimumSize(QtCore.QSize(70, 16))
        self.label_6.setMaximumSize(QtCore.QSize(70, 16))
        self.label_6.setObjectName("label_6")
        self.textBrowser_7 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_7.setGeometry(QtCore.QRect(150, 90, 60, 30))
        self.textBrowser_7.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_7.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.textBrowser_8 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_8.setGeometry(QtCore.QRect(80, 90, 60, 30))
        self.textBrowser_8.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_8.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(80, 140, 60, 30))
        self.textBrowser_4.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.textBrowser_9 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_9.setGeometry(QtCore.QRect(10, 90, 60, 30))
        self.textBrowser_9.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_9.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 40, 16))
        self.label_2.setMinimumSize(QtCore.QSize(40, 16))
        self.label_2.setMaximumSize(QtCore.QSize(40, 16))
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 0, 400, 34))
        self.pushButton.setMinimumSize(QtCore.QSize(400, 34))
        self.pushButton.setMaximumSize(QtCore.QSize(400, 34))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(270, 30, 400, 34))
        self.pushButton_2.setMinimumSize(QtCore.QSize(400, 34))
        self.pushButton_2.setMaximumSize(QtCore.QSize(400, 34))
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(10, 360, 210, 230))
        self.textBrowser.setMinimumSize(QtCore.QSize(210, 230))
        self.textBrowser.setMaximumSize(QtCore.QSize(210, 230))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(450, 360, 210, 230))
        self.textBrowser_2.setMinimumSize(QtCore.QSize(210, 230))
        self.textBrowser_2.setMaximumSize(QtCore.QSize(210, 230))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(10, 340, 160, 16))
        self.label_23.setMinimumSize(QtCore.QSize(160, 16))
        self.label_23.setMaximumSize(QtCore.QSize(160, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(450, 340, 160, 16))
        self.label_24.setMinimumSize(QtCore.QSize(160, 16))
        self.label_24.setMaximumSize(QtCore.QSize(160, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(230, 340, 210, 16))
        self.label_25.setMinimumSize(QtCore.QSize(210, 16))
        self.label_25.setMaximumSize(QtCore.QSize(210, 16))
        self.label_25.setObjectName("label_25")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(230, 360, 210, 230))
        self.textBrowser_3.setMinimumSize(QtCore.QSize(210, 230))
        self.textBrowser_3.setMaximumSize(QtCore.QSize(210, 230))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_12 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_12.setGeometry(QtCore.QRect(390, 280, 80, 30))
        self.textBrowser_12.setMinimumSize(QtCore.QSize(80, 30))
        self.textBrowser_12.setMaximumSize(QtCore.QSize(80, 30))
        self.textBrowser_12.setObjectName("textBrowser_12")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(310, 220, 60, 16))
        self.label_11.setMinimumSize(QtCore.QSize(60, 16))
        self.label_11.setMaximumSize(QtCore.QSize(60, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(321, 261, 40, 16))
        self.label_12.setMinimumSize(QtCore.QSize(40, 16))
        self.label_12.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_12.setObjectName("label_12")
        self.textBrowser_11 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_11.setGeometry(QtCore.QRect(320, 280, 60, 30))
        self.textBrowser_11.setMinimumSize(QtCore.QSize(60, 30))
        self.textBrowser_11.setMaximumSize(QtCore.QSize(60, 30))
        self.textBrowser_11.setObjectName("textBrowser_11")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(481, 261, 30, 16))
        self.label_14.setMinimumSize(QtCore.QSize(30, 16))
        self.label_14.setMaximumSize(QtCore.QSize(30, 16))
        self.label_14.setObjectName("label_14")
        self.textBrowser_14 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_14.setGeometry(QtCore.QRect(480, 280, 80, 30))
        self.textBrowser_14.setMinimumSize(QtCore.QSize(80, 30))
        self.textBrowser_14.setMaximumSize(QtCore.QSize(80, 30))
        self.textBrowser_14.setObjectName("textBrowser_14")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(390, 260, 40, 16))
        self.label_13.setMinimumSize(QtCore.QSize(40, 16))
        self.label_13.setMaximumSize(QtCore.QSize(40, 16))
        self.label_13.setObjectName("label_13")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(310, 240, 255, 26))
        self.comboBox.setMinimumSize(QtCore.QSize(255, 26))
        self.comboBox.setMaximumSize(QtCore.QSize(255, 26))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 310, 260, 34))
        self.pushButton_3.setMinimumSize(QtCore.QSize(260, 34))
        self.pushButton_3.setMaximumSize(QtCore.QSize(260, 34))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(11, 261, 40, 16))
        self.label_18.setMinimumSize(QtCore.QSize(40, 16))
        self.label_18.setMaximumSize(QtCore.QSize(40, 16))
        self.label_18.setObjectName("label_18")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(91, 261, 30, 16))
        self.label_17.setMinimumSize(QtCore.QSize(30, 16))
        self.label_17.setMaximumSize(QtCore.QSize(30, 16))
        self.label_17.setObjectName("label_17")
        self.textBrowser_16 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_16.setGeometry(QtCore.QRect(90, 280, 70, 30))
        self.textBrowser_16.setMinimumSize(QtCore.QSize(70, 30))
        self.textBrowser_16.setMaximumSize(QtCore.QSize(70, 30))
        self.textBrowser_16.setObjectName("textBrowser_16")
        self.textBrowser_18 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_18.setGeometry(QtCore.QRect(170, 280, 130, 30))
        self.textBrowser_18.setMinimumSize(QtCore.QSize(130, 30))
        self.textBrowser_18.setMaximumSize(QtCore.QSize(130, 30))
        self.textBrowser_18.setObjectName("textBrowser_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(170, 260, 140, 16))
        self.label_19.setMinimumSize(QtCore.QSize(140, 16))
        self.label_19.setMaximumSize(QtCore.QSize(140, 16))
        self.label_19.setObjectName("label_19")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(10, 220, 60, 16))
        self.label_16.setMinimumSize(QtCore.QSize(60, 16))
        self.label_16.setMaximumSize(QtCore.QSize(60, 16))
        self.label_16.setObjectName("label_16")
        self.textBrowser_17 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_17.setGeometry(QtCore.QRect(10, 280, 70, 30))
        self.textBrowser_17.setMinimumSize(QtCore.QSize(70, 30))
        self.textBrowser_17.setMaximumSize(QtCore.QSize(70, 30))
        self.textBrowser_17.setObjectName("textBrowser_17")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 240, 295, 26))
        self.comboBox_2.setMinimumSize(QtCore.QSize(295, 26))
        self.comboBox_2.setMaximumSize(QtCore.QSize(295, 26))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 310, 310, 34))
        self.pushButton_4.setMinimumSize(QtCore.QSize(310, 34))
        self.pushButton_4.setMaximumSize(QtCore.QSize(310, 34))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(270, 60, 60, 16))
        self.label_15.setMinimumSize(QtCore.QSize(60, 16))
        self.label_15.setMaximumSize(QtCore.QSize(60, 16))
        self.label_15.setObjectName("label_15")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(260, 80, 235, 26))
        self.comboBox_3.setMinimumSize(QtCore.QSize(235, 26))
        self.comboBox_3.setMaximumSize(QtCore.QSize(235, 26))
        self.comboBox_3.setObjectName("comboBox_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(490, 60, 180, 43))
        self.pushButton_5.setMinimumSize(QtCore.QSize(180, 43))
        self.pushButton_5.setMaximumSize(QtCore.QSize(180, 43))
        self.pushButton_5.setObjectName("pushButton_5")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(260, 120, 235, 26))
        self.comboBox_4.setMinimumSize(QtCore.QSize(235, 26))
        self.comboBox_4.setMaximumSize(QtCore.QSize(235, 26))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(270, 100, 60, 16))
        self.label_20.setMinimumSize(QtCore.QSize(60, 16))
        self.label_20.setMaximumSize(QtCore.QSize(60, 16))
        self.label_20.setObjectName("label_20")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(260, 160, 235, 26))
        self.comboBox_5.setMinimumSize(QtCore.QSize(235, 26))
        self.comboBox_5.setMaximumSize(QtCore.QSize(235, 26))
        self.comboBox_5.setObjectName("comboBox_5")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(270, 140, 150, 16))
        self.label_21.setMinimumSize(QtCore.QSize(150, 16))
        self.label_21.setMaximumSize(QtCore.QSize(150, 16))
        self.label_21.setObjectName("label_21")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(490, 100, 180, 43))
        self.pushButton_6.setMinimumSize(QtCore.QSize(180, 43))
        self.pushButton_6.setMaximumSize(QtCore.QSize(180, 43))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(490, 140, 180, 43))
        self.pushButton_7.setMinimumSize(QtCore.QSize(180, 43))
        self.pushButton_7.setMaximumSize(QtCore.QSize(180, 43))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(570, 230, 100, 120))
        self.pushButton_8.setMinimumSize(QtCore.QSize(100, 120))
        self.pushButton_8.setMaximumSize(QtCore.QSize(100, 120))
        self.pushButton_8.setObjectName("pushButton_8")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(270, 180, 150, 16))
        self.label_22.setMinimumSize(QtCore.QSize(150, 16))
        self.label_22.setMaximumSize(QtCore.QSize(150, 16))
        self.label_22.setObjectName("label_22")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(260, 200, 235, 26))
        self.comboBox_6.setMinimumSize(QtCore.QSize(235, 26))
        self.comboBox_6.setMaximumSize(QtCore.QSize(235, 26))
        self.comboBox_6.setObjectName("comboBox_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(490, 180, 180, 43))
        self.pushButton_9.setMinimumSize(QtCore.QSize(180, 43))
        self.pushButton_9.setMaximumSize(QtCore.QSize(180, 43))
        self.pushButton_9.setObjectName("pushButton_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.menu.addAction(self.action)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Создание нового персонажа"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Характеристики нового персонажа:</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Имя:"))
        self.label_4.setText(_translate("MainWindow", "Телосложение:"))
        self.label_7.setText(_translate("MainWindow", "Харизма:"))
        self.label_3.setText(_translate("MainWindow", "Ловкость:"))
        self.label_5.setText(_translate("MainWindow", "Интеллект:"))
        self.label_6.setText(_translate("MainWindow", "Мудрость:"))
        self.label_2.setText(_translate("MainWindow", "Сила:"))
        self.pushButton.setText(_translate("MainWindow", "Задать стандартные основные характеристики"))
        self.pushButton_2.setText(_translate("MainWindow", "Задать случайные основные характеристики"))
        self.label_23.setText(_translate("MainWindow", "Описание расы:"))
        self.label_24.setText(_translate("MainWindow", "Описание класса:"))
        self.label_25.setText(_translate("MainWindow", "Описание разновидности расы:"))
        self.label_11.setText(_translate("MainWindow", "Оружие:"))
        self.label_12.setText(_translate("MainWindow", "Урон:"))
        self.label_14.setText(_translate("MainWindow", "Вес:"))
        self.label_13.setText(_translate("MainWindow", "Цена:"))
        self.pushButton_3.setText(_translate("MainWindow", "Вывести информацию об оружии"))
        self.label_18.setText(_translate("MainWindow", "Цена:"))
        self.label_17.setText(_translate("MainWindow", "Вес:"))
        self.label_19.setText(_translate("MainWindow", "Помеха скрытности:"))
        self.label_16.setText(_translate("MainWindow", "Броня:"))
        self.pushButton_4.setText(_translate("MainWindow", "Вывести информацию о броне"))
        self.label_15.setText(_translate("MainWindow", "Класс:"))
        self.pushButton_5.setText(_translate("MainWindow", "Вывести информацию\n"
"о классе"))
        self.label_20.setText(_translate("MainWindow", "Раса:"))
        self.label_21.setText(_translate("MainWindow", "Разновидности рас:"))
        self.pushButton_6.setText(_translate("MainWindow", "Вывести информацию\n"
"о расе"))
        self.pushButton_7.setText(_translate("MainWindow", "Вывести информацию\n"
"о разновидности расы"))
        self.pushButton_8.setText(_translate("MainWindow", "Сохранить\n"
"персонажа"))
        self.label_22.setText(_translate("MainWindow", "Доступные заклинания:"))
        self.pushButton_9.setText(_translate("MainWindow", "Узнать подробнее\n"
"о заклинании"))
        self.menu.setTitle(_translate("MainWindow", "Меню"))
        self.action.setText(_translate("MainWindow", "Вернуться в главное меню"))
