from PyQt5 import QtCore, QtWidgets


# Окно описания заклинаний
class descript_spell(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(415, 271)
        MainWindow.setMinimumSize(QtCore.QSize(415, 270))
        MainWindow.setMaximumSize(QtCore.QSize(415, 271))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(190, 30, 210, 230))
        self.textBrowser.setMinimumSize(QtCore.QSize(210, 230))
        self.textBrowser.setMaximumSize(QtCore.QSize(210, 230))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 10, 71, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 101, 16))
        self.label_4.setObjectName("label_4")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 30, 140, 30))
        self.textBrowser_2.setMinimumSize(QtCore.QSize(140, 30))
        self.textBrowser_2.setMaximumSize(QtCore.QSize(140, 30))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_3 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_3.setGeometry(QtCore.QRect(10, 140, 140, 30))
        self.textBrowser_3.setMinimumSize(QtCore.QSize(140, 30))
        self.textBrowser_3.setMaximumSize(QtCore.QSize(140, 30))
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_4.setGeometry(QtCore.QRect(10, 230, 140, 30))
        self.textBrowser_4.setMinimumSize(QtCore.QSize(140, 30))
        self.textBrowser_4.setMaximumSize(QtCore.QSize(140, 30))
        self.textBrowser_4.setObjectName("textBrowser_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Описание заклинания"))
        self.label.setText(_translate("MainWindow", "Описание:"))
        self.label_2.setText(_translate("MainWindow", "Уровень:"))
        self.label_3.setText(_translate("MainWindow", "Дистанция:"))
        self.label_4.setText(_translate("MainWindow", "Длительность:"))